### ISSUE TITLE
 postges 16

### ISSUE THREAD

**Issue by robertbruno** [AbdulYadi/pgqr#3]
I am compiling this library for postges 16 on a debian 12 and the compilation ends with three (3)  errors

![image](https://github.com/AbdulYadi/pgqr/assets/12821324/3e00742e-39da-4ec6-b7ba-1074b78f385c)

**Comment by etalatam** [comment]
**I was able to resolve the compilation issue for PostgreSQL 16 and 17 by including the `varatt.h` header.**

 It seems that the required definitions for `varatt.h` have been modified or added in these newer PostgreSQL versions. By explicitly including this header, the compiler can find the necessary declarations and successfully build the extension.

 **To implement this solution:**
 1. **Locate the relevant source file(s):** Identify the C/C++ files in your extension where the missing declarations were causing the compilation errors.
 2. **Add the include directive:** At the beginning of these files, add the following line:
   ```c++
   #include "varatt.h"
   ```
 3. **Recompile the extension:** Rebuild your extension using the updated source files.

 **Additional considerations:**
 * **Conditional inclusion:** If you want to maintain compatibility with older PostgreSQL versions, you can use conditional compilation directives (e.g., `#ifdef` and `#endif`) to include `varatt.h` only when compiling for PostgreSQL 16 or 17.
 * **Dependency management:** Ensure that your build system is configured correctly to find the `varatt.h` header file. This might involve setting appropriate include paths.

**Comment by robertbruno** [comment]
**I was able to resolve the compilation issue for PostgreSQL 16 and 17 by including the `varatt.h` header.**

 It seems that the required definitions for `varatt.h` have been modified or added in these newer PostgreSQL versions. By explicitly including this header, the compiler can find the necessary declarations and successfully build the extension.

 **To implement this solution:**
 1. **Locate the relevant source file(s):** Identify the C/C++ files in your extension where the missing declarations were causing the compilation errors.
 2. **Add the include directive:** At the beginning of these files, add the following line:
   ```c++
   #include "varatt.h"
   ```
 3. **Recompile the extension:** Rebuild your extension using the updated source files.

 **Additional considerations:**
 * **Conditional inclusion:** If you want to maintain compatibility with older PostgreSQL versions, you can use conditional compilation directives (e.g., `#ifdef` and `#endif`) to include `varatt.h` only when compiling for PostgreSQL 16 or 17.
 * **Dependency management:** Ensure that your build system is configured correctly to find the `varatt.h` header file. This might involve setting appropriate include paths.

**Comment by robertbruno** [comment]
I close this issue in order to give attention to only one #4
